return {
  'mason-org/mason-lspconfig.nvim',
  dependencies = {
    { 'mason-org/mason.nvim', opts = {} },
    'neovim/nvim-lspconfig',
  },
  opts = {
    ensure_installed = {
      -- 'bashls',
      'clangd',
      -- 'cssls',
      -- 'dockerls',
      'glsl_analyzer',
      -- 'gopls',
      -- 'graphql',
      -- 'html',
      -- 'jdtls',
      -- 'jsonls',
      -- 'kotlin_language_server',
      -- 'lemminx',
      'lua_ls',
      -- 'marksman',
      -- 'ols',
      -- 'omnisharp',
      -- 'omnisharp_mono',
      -- 'postgres_lsp',
      -- 'powershell_es',
      -- 'pyright',
      -- 'rust_analyzer',
      -- 'tailwindcss',
      -- 'taplo',
      -- 'texlab',
      -- 'ts_ls',
      -- 'verible',
      -- 'yamlls',
      -- 'zls',
    },
  },
}
