require('mason').setup()
require('mason-lspconfig').setup {
  ensure_installed = {
    -- 'bashls',
    'clangd',
    -- 'csharp_ls',
    -- 'cssls',
    -- 'dockerls',
    'glsl_analyzer',
    -- 'gopls',
    -- 'graphql',
    -- 'html',
    -- 'jdtls',
    'jsonls',
    -- 'kotlin_language_server',
    -- 'lemminx',
    'lua_ls',
    -- 'marksman',
    -- 'ols',
    -- 'omnisharp',
    -- 'omnisharp_mono',
    -- 'postgres_lsp',
    'powershell_es',
    -- 'pyright',
    -- 'rust_analyzer',
    -- 'tailwindcss',
    'taplo',
    'texlab',
    -- 'ts_ls',
    -- 'verible',
    -- 'yamlls',
    -- 'zls',
  },
}
require('mason-tool-installer').setup {
  ensure_installed = {
    'black',
    'clang-format',
    'gdtoolkit',
    'gersemi',
    'ktfmt',
    'prettier',
    'shfmt',
    'sqruff',
    'stylua',
    'taplo',
    'tex-fmt',
    'yamlfmt',
  },
}
